from ticket_to_ride_api import *

colors = {
    0: 'gray',
    1: 'yellow',
    2: 'orange',
    3: 'blue',
    4: 'violet',
    5: 'black',
    6: 'white',
    7: 'green',
    8: 'red'
}

cities = {
    City('Kobenhavn'),
    City('Arhus'),
    City('Alborg'),
    City('Karlskrona'),
    City('Goteborg'),
    City('Stavanger'),
    City('Kristiansand'),
    City('Norrkoping'),
    City('Oslo'),
    City('Bergen'),
    City('Stockholm'),
    City('Orebro'),
    City('Lillehammer'),
    City('Tallinn'),
    City('Helsinki'),
    City('Turku'),
    City('Trondheim'),
    City('Andalsnes'),
    City('Sundsvall'),
    City('Lahti'),
    City('Tampere'),
    City('Ostersund'),
    City('Imatra'),
    City('Vaasa'),
    City('Umea'),
    City('Kuopio'),
    City('Moirana'),
    City('Lieksa'),
    City('Oulu'),
    City('Kajaani'),
    City('Boden'),
    City('Tornio'),
    City('Kiruna'),
    City('Rovaniemi'),
    City('Narvik'),
    City('Tromso'),
    City('Kirkenes'),
    City('Murmansk'),
    City('Honningsvag')
}

roads = [
    Road(start=City('Arhus'), end=City('Kobenhavn'), color=0, length=1,loco=1, tonnel=False),
    Road(start=City('Arhus'), end=City('Alborg'), color=4, length=1,loco=0, tonnel=False),
    Road(start=City('Kobenhavn'), end=City('Karlskrona'), color=3, length=2,loco=1, tonnel=False),
    Road(start=City('Kobenhavn'), end=City('Karlskrona'), color=7, length=2, loco=1, tonnel=False),
    Road(start=City('Kobenhavn'), end=City('Goteborg'), color=5, length=2,loco=1, tonnel=False),
    Road(start=City('Alborg'), end=City('Goteborg'), color=0, length=2,loco=1, tonnel=False),
    Road(start=City('Alborg'), end=City('Oslo'), color=6, length=3, loco=1, tonnel=False),
    Road(start=City('Alborg'), end=City('Kristiansand'), color=8, length=2, loco=1, tonnel=False),
    Road(start=City('Karlskrona'), end=City('Norrkoping'), color=6, length=3, loco=0, tonnel=False),
    Road(start=City('Karlskrona'), end=City('Norrkoping'), color=1, length=3, loco=0, tonnel=False),
    Road(start=City('Goteborg'), end=City('Norrkoping'), color=0, length=3, loco=0, tonnel=False),
    Road(start=City('Goteborg'), end=City('Orebro'), color=3, length=2, loco=0, tonnel=False),
    Road(start=City('Goteborg'), end=City('Oslo'), color=2, length=2, loco=0, tonnel=False),
    Road(start=City('Krisiansand'), end=City('Stavanger'), color=2, length=3, loco=1, tonnel=False),
    Road(start=City('Krisiansand'), end=City('Stavanger'), color=7, length=2, loco=0, tonnel=True),
    Road(start=City('Krisiansand'), end=City('Oslo'), color=5, length=2, loco=0, tonnel=False),
    Road(start=City('Stavanger'), end=City('Bergen'), color=4, length=2, loco=1, tonnel=False),
    Road(start=City('Bergen'), end=City('Oslo'), color=8, length=4, loco=0, tonnel=True),
    Road(start=City('Bergen'), end=City('Oslo'), color=3, length=4, loco=0, tonnel=True),
    Road(start=City('Bergen'), end=City('Andalsnes'), color=5, length=5, loco=2, tonnel=False),
    Road(start=City('Oslo'), end=City('Lillehammer'), color=4, length=2, loco=0, tonnel=True),
    Road(start=City('Oslo'), end=City('Orebro'), color=1, length=2, loco=0, tonnel=False),
    Road(start=City('Oslo'), end=City('Orebro'), color=7, length=2, loco=0, tonnel=False),
    Road(start=City('Orebro'), end=City('Sundsvall'), color=2, length=4, loco=0, tonnel=False),
    Road(start=City('Orebro'), end=City('Norrkoping'), color=0, length=2, loco=0, tonnel=False),
    Road(start=City('Orebro'), end=City('Stockholm'), color=5, length=2, loco=0, tonnel=False),
    Road(start=City('Orebro'), end=City('Stockholm'), color=4, length=2, loco=0, tonnel=False),
    Road(start=City('Norrkoping'), end=City('Stockholm'), color=2, length=1, loco=0, tonnel=False),
    Road(start=City('Norrkoping'), end=City('Stockholm'), color=8, length=1, loco=0, tonnel=False),
    Road(start=City('Lillehammer'), end=City('Andalsnes'), color=1, length=2, loco=0, tonnel=True),
    Road(start=City('Lillehammer'), end=City('Trondheim'), color=2, length=3, loco=0, tonnel=True),
    Road(start=City('Stockholm'), end=City('Tallin'), color=7, length=4, loco=2, tonnel=False),
    Road(start=City('Stockholm'), end=City('Helsinki'), color=0, length=4, loco=2, tonnel=False),
    Road(start=City('Stockholm'), end=City('Helsinki'), color=1, length=4, loco=1, tonnel=False),
    Road(start=City('Stockholm'), end=City('Turku'), color=3, length=3, loco=1, tonnel=False),
    Road(start=City('Stockholm'), end=City('Sundsvall'), color=0, length=4, loco=0, tonnel=False),
    Road(start=City('Stockholm'), end=City('Sundsvall'), color=0, length=4, loco=0, tonnel=False),
    Road(start=City('Andalsnes'), end=City('Trondheim'), color=6, length=2, loco=1, tonnel=False),
    Road(start=City('Trondheim'), end=City('Ostersund'), color=5, length=2, loco=0, tonnel=True),
    Road(start=City('Trondheim'), end=City('Moirana'), color=7, length=5, loco=0, tonnel=True),
    Road(start=City('Trondheim'), end=City('Moirana'), color=8, length=6, loco=2, tonnel=False),
    Road(start=City('Ostersund'), end=City('Sundsvall'), color=7, length=2, loco=0, tonnel=False),
    Road(start=City('Sundsvall'), end=City('Umea'), color=4, length=3, loco=0, tonnel=False),
    Road(start=City('Sundsvall'), end=City('Umea'), color=1, length=3, loco=0, tonnel=False),
    Road(start=City('Sundsvall'), end=City('Vaasa'), color=3, length=3, loco=1, tonnel=False),
    Road(start=City('Turku'), end=City('Helsinki'), color=6, length=1, loco=0, tonnel=False),
    Road(start=City('Turku'), end=City('Tampere'), color=8, length=1, loco=0, tonnel=False),
    Road(start=City('Tallinn'), end=City('Helsinki'), color=4, length=2, loco=1, tonnel=False),
    Road(start=City('Helsinki'), end=City('Lahti'), color=5, length=1, loco=0, tonnel=False),
    Road(start=City('Helsinki'), end=City('Tampere'), color=2, length=1, loco=0, tonnel=False),
    Road(start=City('Helsinki'), end=City('Imatra'), color=8, length=3, loco=0, tonnel=False),
    Road(start=City('Imatra'), end=City('Lahti'), color=1, length=2, loco=0, tonnel=False),
    Road(start=City('Imatra'), end=City('Kuopio'), color=4, length=2, loco=0, tonnel=False),
    Road(start=City('Lahti'), end=City('Kuopio'), color=6, length=3, loco=0, tonnel=False),
    Road(start=City('Lahti'), end=City('Tampere'), color=3, length=1, loco=0, tonnel=False),
    Road(start=City('Tampere'), end=City('Vaasa'), color=4, length=2, loco=0, tonnel=False),
    Road(start=City('Kuopio'), end=City('Lieksa'), color=5, length=1, loco=0, tonnel=False),
    Road(start=City('Kuopio'), end=City('Kajani'), color=7, length=2, loco=0, tonnel=False),
    Road(start=City('Kuopio'), end=City('Oulu'), color=0, length=3, loco=0, tonnel=False),
    Road(start=City('Kuopio'), end=City('Vaasa'), color=0, length=4, loco=0, tonnel=False),
    Road(start=City('Vaasa'), end=City('Oulu'), color=5, length=3, loco=0, tonnel=False),
    Road(start=City('Vaasa'), end=City('Umea'), color=0, length=1, loco=1, tonnel=False),
    Road(start=City('Umea'), end=City('Boden'), color=6, length=3, loco=0, tonnel=False),
    Road(start=City('Umea'), end=City('Boden'), color=8, length=3, loco=0, tonnel=False),
    Road(start=City('Moirana'), end=City('Narvik'), color=2, length=4, loco=2, tonnel=False),
    Road(start=City('Narvik'), end=City('Tromso'), color=1, length=3, loco=1, tonnel=False),
    Road(start=City('Narvik'), end=City('Kiruna'), color=6, length=1, loco=0, tonnel=True),
    Road(start=City('Narvik'), end=City('Kiruna'), color=4, length=1, loco=0, tonnel=True),
    Road(start=City('Kiruna'), end=City('Boden'), color=2, length=3, loco=0, tonnel=False),
    Road(start=City('Kiruna'), end=City('Boden'), color=5, length=3, loco=0, tonnel=False),
    Road(start=City('Boden'), end=City('Tornio'), color=7, length=1, loco=0, tonnel=False),
    Road(start=City('Tornio'), end=City('Oulu'), color=6, length=1, loco=0, tonnel=False),
    Road(start=City('Tornio'), end=City('Rovaniemi'), color=8, length=2, loco=0, tonnel=False),
    Road(start=City('Oulu'), end=City('Rovaniemi'), color=2, length=2, loco=0, tonnel=False),
    Road(start=City('Oulu'), end=City('Kajaani'), color=1, length=2, loco=0, tonnel=False),
    Road(start=City('Kajaani'), end=City('Lieksa'), color=3, length=1, loco=0, tonnel=False),
    Road(start=City('Lieksa'), end=City('Murmansk'), color=0, length=9, loco=0, tonnel=False),
    Road(start=City('Rovaniemi'), end=City('Kirkenes'), color=3, length=5, loco=0, tonnel=False),
    Road(start=City('Tromso'), end=City('Honningsvag'), color=4, length=4, loco=2, tonnel=False),
    Road(start=City('Honningsvag'), end=City('Kirkenes'), color=7, length=2, loco=1, tonnel=False),
    Road(start=City('Kirkenes'), end=City('Murmansk'), color=6, length=3, loco=1, tonnel=False),
]