from ticket_to_ride_api import *

colors = {
    0: 'gray',
    1: 'yellow',
    2: 'orange',
    3: 'blue',
    4: 'violet',
    5: 'black',
    6: 'white',
    7: 'green',
    8: 'red'
}

CITIES = {
    'Kobenhavn': City('Kobenhavn'),
    'Arhus': City('Arhus'),
    'Alborg': City('Alborg'),
    'Karlskrona': City('Karlskrona'),
    'Goteborg': City('Goteborg'),
    'Stavanger': City('Stavanger'),
    'Kristiansand': City('Kristiansand'),
    'Norrkoping': City('Norrkoping'),
    'Oslo': City('Oslo'),
    'Bergen': City('Bergen'),
    'Stockholm': City('Stockholm'),
    'Orebro': City('Orebro'),
    'Lillehammer': City('Lillehammer'),
    'Tallinn': City('Tallinn'),
    'Helsinki': City('Helsinki'),
    'Turku': City('Turku'),
    'Trondheim': City('Trondheim'),
    'Andalsnes': City('Andalsnes'),
    'Sundsvall': City('Sundsvall'),
    'Lahti': City('Lahti'),
    'Tampere': City('Tampere'),
    'Ostersund': City('Ostersund'),
    'Imatra': City('Imatra'),
    'Vaasa': City('Vaasa'),
    'Umea': City('Umea'),
    'Kuopio': City('Kuopio'),
    'Moirana': City('Moirana'),
    'Lieksa': City('Lieksa'),
    'Oulu': City('Oulu'),
    'Kajaani': City('Kajaani'),
    'Boden': City('Boden'),
    'Tornio': City('Tornio'),
    'Kiruna': City('Kiruna'),
    'Rovaniemi': City('Rovaniemi'),
    'Narvik': City('Narvik'),
    'Tromso': City('Tromso'),
    'Kirkenes': City('Kirkenes'),
    'Murmansk': City('Murmansk'),
    'Honningsvag': City('Honningsvag')
}

roads = [
    Road(start=CITIES['Arhus'], end=CITIES['Kobenhavn'], color=0, length=1,loco=1, tonnel=False),
    Road(start=CITIES['Arhus'], end=CITIES['Alborg'], color=4, length=1,loco=0, tonnel=False),
    Road(start=CITIES['Kobenhavn'], end=CITIES['Karlskrona'], color=3, length=2,loco=1, tonnel=False),
    Road(start=CITIES['Kobenhavn'], end=CITIES['Karlskrona'], color=7, length=2, loco=1, tonnel=False),
    Road(start=CITIES['Kobenhavn'], end=CITIES['Goteborg'], color=5, length=2,loco=1, tonnel=False),
    Road(start=CITIES['Alborg'], end=CITIES['Goteborg'], color=0, length=2,loco=1, tonnel=False),
    Road(start=CITIES['Alborg'], end=CITIES['Oslo'], color=6, length=3, loco=1, tonnel=False),
    Road(start=CITIES['Alborg'], end=CITIES['Kristiansand'], color=8, length=2, loco=1, tonnel=False),
    Road(start=CITIES['Karlskrona'], end=CITIES['Norrkoping'], color=6, length=3, loco=0, tonnel=False),
    Road(start=CITIES['Karlskrona'], end=CITIES['Norrkoping'], color=1, length=3, loco=0, tonnel=False),
    Road(start=CITIES['Goteborg'], end=CITIES['Norrkoping'], color=0, length=3, loco=0, tonnel=False),
    Road(start=CITIES['Goteborg'], end=CITIES['Orebro'], color=3, length=2, loco=0, tonnel=False),
    Road(start=CITIES['Goteborg'], end=CITIES['Oslo'], color=2, length=2, loco=0, tonnel=False),
    Road(start=CITIES['Kristiansand'], end=CITIES['Stavanger'], color=2, length=3, loco=1, tonnel=False),
    Road(start=CITIES['Kristiansand'], end=CITIES['Stavanger'], color=7, length=2, loco=0, tonnel=True),
    Road(start=CITIES['Kristiansand'], end=CITIES['Oslo'], color=5, length=2, loco=0, tonnel=False),
    Road(start=CITIES['Stavanger'], end=CITIES['Bergen'], color=4, length=2, loco=1, tonnel=False),
    Road(start=CITIES['Bergen'], end=CITIES['Oslo'], color=8, length=4, loco=0, tonnel=True),
    Road(start=CITIES['Bergen'], end=CITIES['Oslo'], color=3, length=4, loco=0, tonnel=True),
    Road(start=CITIES['Bergen'], end=CITIES['Andalsnes'], color=5, length=5, loco=2, tonnel=False),
    Road(start=CITIES['Oslo'], end=CITIES['Lillehammer'], color=4, length=2, loco=0, tonnel=True),
    Road(start=CITIES['Oslo'], end=CITIES['Orebro'], color=1, length=2, loco=0, tonnel=False),
    Road(start=CITIES['Oslo'], end=CITIES['Orebro'], color=7, length=2, loco=0, tonnel=False),
    Road(start=CITIES['Orebro'], end=CITIES['Sundsvall'], color=2, length=4, loco=0, tonnel=False),
    Road(start=CITIES['Orebro'], end=CITIES['Norrkoping'], color=0, length=2, loco=0, tonnel=False),
    Road(start=CITIES['Orebro'], end=CITIES['Stockholm'], color=5, length=2, loco=0, tonnel=False),
    Road(start=CITIES['Orebro'], end=CITIES['Stockholm'], color=4, length=2, loco=0, tonnel=False),
    Road(start=CITIES['Norrkoping'], end=CITIES['Stockholm'], color=2, length=1, loco=0, tonnel=False),
    Road(start=CITIES['Norrkoping'], end=CITIES['Stockholm'], color=8, length=1, loco=0, tonnel=False),
    Road(start=CITIES['Lillehammer'], end=CITIES['Andalsnes'], color=1, length=2, loco=0, tonnel=True),
    Road(start=CITIES['Lillehammer'], end=CITIES['Trondheim'], color=2, length=3, loco=0, tonnel=True),
    Road(start=CITIES['Stockholm'], end=CITIES['Tallinn'], color=7, length=4, loco=2, tonnel=False),
    Road(start=CITIES['Stockholm'], end=CITIES['Helsinki'], color=0, length=4, loco=2, tonnel=False),
    Road(start=CITIES['Stockholm'], end=CITIES['Helsinki'], color=1, length=4, loco=1, tonnel=False),
    Road(start=CITIES['Stockholm'], end=CITIES['Turku'], color=3, length=3, loco=1, tonnel=False),
    Road(start=CITIES['Stockholm'], end=CITIES['Sundsvall'], color=0, length=4, loco=0, tonnel=False),
    Road(start=CITIES['Stockholm'], end=CITIES['Sundsvall'], color=0, length=4, loco=0, tonnel=False),
    Road(start=CITIES['Andalsnes'], end=CITIES['Trondheim'], color=6, length=2, loco=1, tonnel=False),
    Road(start=CITIES['Trondheim'], end=CITIES['Ostersund'], color=5, length=2, loco=0, tonnel=True),
    Road(start=CITIES['Trondheim'], end=CITIES['Moirana'], color=7, length=5, loco=0, tonnel=True),
    Road(start=CITIES['Trondheim'], end=CITIES['Moirana'], color=8, length=6, loco=2, tonnel=False),
    Road(start=CITIES['Ostersund'], end=CITIES['Sundsvall'], color=7, length=2, loco=0, tonnel=False),
    Road(start=CITIES['Sundsvall'], end=CITIES['Umea'], color=4, length=3, loco=0, tonnel=False),
    Road(start=CITIES['Sundsvall'], end=CITIES['Umea'], color=1, length=3, loco=0, tonnel=False),
    Road(start=CITIES['Sundsvall'], end=CITIES['Vaasa'], color=3, length=3, loco=1, tonnel=False),
    Road(start=CITIES['Turku'], end=CITIES['Helsinki'], color=6, length=1, loco=0, tonnel=False),
    Road(start=CITIES['Turku'], end=CITIES['Tampere'], color=8, length=1, loco=0, tonnel=False),
    Road(start=CITIES['Tallinn'], end=CITIES['Helsinki'], color=4, length=2, loco=1, tonnel=False),
    Road(start=CITIES['Helsinki'], end=CITIES['Lahti'], color=5, length=1, loco=0, tonnel=False),
    Road(start=CITIES['Helsinki'], end=CITIES['Tampere'], color=2, length=1, loco=0, tonnel=False),
    Road(start=CITIES['Helsinki'], end=CITIES['Imatra'], color=8, length=3, loco=0, tonnel=False),
    Road(start=CITIES['Imatra'], end=CITIES['Lahti'], color=1, length=2, loco=0, tonnel=False),
    Road(start=CITIES['Imatra'], end=CITIES['Kuopio'], color=4, length=2, loco=0, tonnel=False),
    Road(start=CITIES['Lahti'], end=CITIES['Kuopio'], color=6, length=3, loco=0, tonnel=False),
    Road(start=CITIES['Lahti'], end=CITIES['Tampere'], color=3, length=1, loco=0, tonnel=False),
    Road(start=CITIES['Tampere'], end=CITIES['Vaasa'], color=4, length=2, loco=0, tonnel=False),
    Road(start=CITIES['Kuopio'], end=CITIES['Lieksa'], color=5, length=1, loco=0, tonnel=False),
    Road(start=CITIES['Kuopio'], end=CITIES['Kajaani'], color=7, length=2, loco=0, tonnel=False),
    Road(start=CITIES['Kuopio'], end=CITIES['Oulu'], color=0, length=3, loco=0, tonnel=False),
    Road(start=CITIES['Kuopio'], end=CITIES['Vaasa'], color=0, length=4, loco=0, tonnel=False),
    Road(start=CITIES['Vaasa'], end=CITIES['Oulu'], color=5, length=3, loco=0, tonnel=False),
    Road(start=CITIES['Vaasa'], end=CITIES['Umea'], color=0, length=1, loco=1, tonnel=False),
    Road(start=CITIES['Umea'], end=CITIES['Boden'], color=6, length=3, loco=0, tonnel=False),
    Road(start=CITIES['Umea'], end=CITIES['Boden'], color=8, length=3, loco=0, tonnel=False),
    Road(start=CITIES['Moirana'], end=CITIES['Narvik'], color=2, length=4, loco=2, tonnel=False),
    Road(start=CITIES['Narvik'], end=CITIES['Tromso'], color=1, length=3, loco=1, tonnel=False),
    Road(start=CITIES['Narvik'], end=CITIES['Kiruna'], color=6, length=1, loco=0, tonnel=True),
    Road(start=CITIES['Narvik'], end=CITIES['Kiruna'], color=4, length=1, loco=0, tonnel=True),
    Road(start=CITIES['Kiruna'], end=CITIES['Boden'], color=2, length=3, loco=0, tonnel=False),
    Road(start=CITIES['Kiruna'], end=CITIES['Boden'], color=5, length=3, loco=0, tonnel=False),
    Road(start=CITIES['Boden'], end=CITIES['Tornio'], color=7, length=1, loco=0, tonnel=False),
    Road(start=CITIES['Tornio'], end=CITIES['Oulu'], color=6, length=1, loco=0, tonnel=False),
    Road(start=CITIES['Tornio'], end=CITIES['Rovaniemi'], color=8, length=2, loco=0, tonnel=False),
    Road(start=CITIES['Oulu'], end=CITIES['Rovaniemi'], color=2, length=2, loco=0, tonnel=False),
    Road(start=CITIES['Oulu'], end=CITIES['Kajaani'], color=1, length=2, loco=0, tonnel=False),
    Road(start=CITIES['Kajaani'], end=CITIES['Lieksa'], color=3, length=1, loco=0, tonnel=False),
    Road(start=CITIES['Lieksa'], end=CITIES['Murmansk'], color=0, length=9, loco=0, tonnel=False),
    Road(start=CITIES['Rovaniemi'], end=CITIES['Kirkenes'], color=3, length=5, loco=0, tonnel=False),
    Road(start=CITIES['Tromso'], end=CITIES['Honningsvag'], color=4, length=4, loco=2, tonnel=False),
    Road(start=CITIES['Honningsvag'], end=CITIES['Kirkenes'], color=7, length=2, loco=1, tonnel=False),
    Road(start=CITIES['Kirkenes'], end=CITIES['Murmansk'], color=6, length=3, loco=1, tonnel=False),
]

def check_up():
    board = Board()
    board.add_cities(CITIES.values())
    for road in roads:
        if not board.check([road]):
            print(road)
    print("check_up finished")